export const DEFAULT_OPENAI_EMBEDDING_MODEL = 'text-embedding-3-large';

export const CLOUDFLARE_ERROR_CODE_VECTOR_INDEX_NOT_FOUND = 3000;
export const CLOUDFLARE_ERROR_CODE_INSERT_VECTOR_INDEX_SIZE_MISMATCH = 4003;