export const CLOUDFLARE_ERROR_CODE_VECTOR_INDEX_NOT_FOUND = 3000;
export const CLOUDFLARE_ERROR_CODE_INSERT_VECTOR_INDEX_SIZE_MISMATCH = 4003;

export const OPENAI_EMBEDDING_MODEL_SMALL = 'text-embedding-3-small';
export const OPENAI_EMBEDDING_MODEL_LARGE = 'text-embedding-3-large';
export const OPENAI_EMBEDDING_MODEL_ADA_002 = 'text-embedding-ada-002';
export const OPENAI_EMBEDDING_MODELS = [OPENAI_EMBEDDING_MODEL_SMALL, OPENAI_EMBEDDING_MODEL_LARGE, OPENAI_EMBEDDING_MODEL_ADA_002];